### PR TITLE
Changes row/column order

### PR DESCRIPTION
**Pull request by ldybal**

### CODE REVIEW

**Comment by yesoreyeram** [comment]
Hi @ldybal - Thanks for the contribution.

BTW, I can't approve this PR as it is. If someone have big tooltip template, then definetly tooltip is hiding behind if set to "top".  See below

Tooltip with "Top" position ( 2 nd row )

image

but first row is not correct. Some of the tooltip is not showing up.

image

If you could split this into two,  I am happy to approve and merge the sorting one.

**Comment by yesoreyeram** [comment]
BTW, have you tested the sorting? ( Clicking table headers )

**Comment by ldybal** [comment]
My example had hidden headers, but I just changed to "un-hidden" and the sorting by clicking on the column header still works

________________________________

**Comment by yesoreyeram** [comment]
Sorry @ldybal  for the delay merging this.  Thanks for the contribution.

**Pull request merged**
