### PR TITLE
fixing panel scrolling based on ctrl height

### PR DESCRIPTION
**Pull request by yesoreyeram**
Creates scrollbar based on ctrl height

image

### CODE REVIEW

**Comment by JosephFY** [comment]
Hello, did this ever get implemented. Couldn't see it in the recent version ? it's really cool to have this feature. without it the dashboard cannot be dynamic which is really hard to design

**Comment by yesoreyeram** [comment]
It is already implemented and merged long back. Could you share more details of the versions you r using? It has both horizontal and vertical scroll bars

image

**Comment by JosephFY** [comment]
Thank you for the quick response,
0.4.6 panel 
4.4.3 Grafana

Is there anywhere to enable it that I am overlooking ?

**Comment by yesoreyeram** [comment]
Strange. Thats enabled by default. May be clear cache / try in incognito mode. ( BTW, i haven't tested in grafana 4.x .  )

**Comment by JosephFY** [comment]
It's working now. my bad, something to do with a bug for the rows heights in Grafana. adding new row and panel did it for me. I really should get my Grafana instance upgraded :)
Thank you again for the quick response

**Pull request merged**
